# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SG-Portfolio-NextJS-CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      
      - name: "Copy env file to root directory"
        run: cp ${{secrets.ENV_FILE_LOCATION}} ./

      - run: npm run build --if-present

      - name: Remove existing App directory if it exist
        run: rm -rf ${{secrets.APP_ROOT_DIRECTORY}}

      - name: Create a fresh App directory
        run: mkdir -p ${{secrets.APP_ROOT_DIRECTORY}}

      - name: Moving App from runner directory to designated directory
        run: mv -f ${{secrets.APP_LOCATION_IN_RUNNER_DIRECTORY}}* ${{secrets.APP_ROOT_DIRECTORY}}

      - name: Moving App all files from runner directory to designated directory
        run: mv -f ${{secrets.APP_LOCATION_IN_RUNNER_DIRECTORY}}.[!.]*  ${{secrets.APP_ROOT_DIRECTORY}}

      - name: Re-start PM2 process
        run: pm2 restart SG-portfolio-nextjs

      

